### ISSUE TITLE
Errors when running server on RHEL8

### ISSUE THREAD

**Issue by s-andrews** [DesmondWillowbrook/Librarian-Server#3]
```
[andrewss@bioinform server]$ cargo run --bin server --release
    Finished release [optimized] target(s) in 0.39s
     Running `target/release/server`
Starting application
2022-05-10 14:28:22,959 TRACE [actix_web::middleware::logger] Access log format: %a "%r" %s %b "%{Referer}i" "%{User-Agent}i" %T
2022-05-10 14:28:22,959 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,959 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,959 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,959 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,959 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,959 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,960 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,960 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,961 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,961 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,961 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,961 TRACE [mio::poll] registering with poller
thread '2022-05-10 14:28:22,961 TRACE [mio::poll] registering with poller
actix-rt:worker:1' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())2022-05-10 14:28:22,961 TRACE [mio::poll] registering with poller
', src/bin/server.rs:55:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-05-10 14:28:22,961 TRACE [actix_server::worker] Service "actix-web-service-0.0.0.0:8186" is available
2022-05-10 14:28:22,962 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:4' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,962 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,962 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:5' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,962 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:2' panicked at '2022-05-10 14:28:22,962 TRACE [mio::poll] registering with poller
called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,962 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:6' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,962 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:3' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,962 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,962 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:7' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread '2022-05-10 14:28:22,963 TRACE [mio::poll] registering with poller
actix-rt:worker:8' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }2022-05-10 14:28:22,963 TRACE [mio::poll] registering with poller
', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:9' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:2022-05-10 14:28:22,963 TRACE [mio::poll] registering with poller
282:36
2022-05-10 14:28:22,963 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,963 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:28' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,963 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:12' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:362022-05-10 14:28:22,963 TRACE [mio::poll] registering with poller

2022-05-10 14:28:22,963 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:11' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,964 TRACE [mio::poll] registering with poller
thread '2022-05-10 14:28:22,964 TRACE [mio::poll] registering with poller
actix-rt:worker:13' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,964 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:14' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,964 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,964 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:15' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,964 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:16' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:17' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', 2022-05-10 14:28:22,965 TRACE [mio::poll] registering with poller
/home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,965 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:18' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,965 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:20' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs2022-05-10 14:28:22,965 TRACE [mio::poll] registering with poller
:282:36
2022-05-10 14:28:22,965 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:192022-05-10 14:28:22,965 TRACE [mio::poll] registering with poller
' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,966 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:21' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,966 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:22' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,966 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:24' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs2022-05-10 14:28:22,966 TRACE [mio::poll] registering with poller
:282:36
thread 'actix-rt:worker:23' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }2022-05-10 14:28:22,966 TRACE [mio::poll] registering with poller
', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,966 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:26' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:50' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,966 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,966 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:27' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,966 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:10' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:2022-05-10 14:28:22,967 TRACE [mio::poll] registering with poller
36
thread 'actix-rt:worker:29' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:2022-05-10 14:28:22,967 TRACE [mio::poll] registering with poller
36
thread 'actix-rt:worker:55' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,967 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:31' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,967 TRACE [mio::poll] registering with poller
thread '2022-05-10 14:28:22,967 TRACE [mio::poll] registering with poller
actix-rt:worker:32' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,967 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:34' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,967 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:33' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,967 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:35' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }2022-05-10 14:28:22,968 INFO [actix_server::builder] Starting "actix-web-service-0.0.0.0:8186" service on 0.0.0.0:8186
', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs2022-05-10 14:28:22,968 TRACE [mio::poll] registering with poller
:282:36
2022-05-10 14:28:22,968 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:36' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
2022-05-10 14:28:22,968 TRACE [mio::poll] registering with poller
thread 'actix-rt:worker:37' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', 2022-05-10 14:28:22,968 TRACE [mio::poll] registering with poller
/home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:2822022-05-10 14:28:22,968 TRACE [mio::poll] registering with poller
:36
2022-05-10 14:28:22,968 TRACE [mio::poll] registering with poller
2022-05-10 14:28:22,968 TRACE [mio::poll] registering with poller
thread '2022-05-10 14:28:22,968 TRACE [mio::poll] registering with poller
actix-rt:worker:39' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs2022-05-10 14:28:22,968 TRACE [mio::poll] registering with poller
:282:362022-05-10 14:28:22,968 TRACE [mio::poll] registering with poller

thread 'actix-rt:worker:38' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:40' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:41' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:42' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:43' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:44' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:45' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:46' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:47' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:48' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:49' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:25' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:51' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:52' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:53' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:54' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:30' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:56' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:57' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:58' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:59' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:60' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:61' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:62' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:63' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/andrewss/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36

```

**Comment by DesmondWillowbrook** [comment]
I don't see anywhere that the process actually exited due to a fatal error.

The web server is a bit verbose, and a bunch of `PoisonError`s show up during startup for some reason that I haven't investigated.

I've toned down the verbosity of the logging now, so let me know if there's any issue.

**Comment by s-andrews** [comment]
The server did run before (albeit with errors).  I've pulled the new version and now it doesn't start:

```
error: there is no argument named `default`
  --> src/bin/server.rs:56:60
   |
56 |                 warn!("{:?} not found, using default value {default:?}", &key);
   |                                                            ^^^^^^^^^^^

error: aborting due to previous error

```

This is the full verbose output.

```
[andrewss@bioinform server]$ cargo run --bin server --release --verbose
       Fresh unicode-xid v0.2.2
       Fresh cfg-if v1.0.0
       Fresh autocfg v1.0.1
       Fresh version_check v0.9.3
       Fresh lazy_static v1.4.0
       Fresh cc v1.0.69
       Fresh slab v0.4.4
       Fresh futures-sink v0.3.16
       Fresh bytes v0.5.6
       Fresh cfg-if v0.1.10
       Fresh pin-project-lite v0.2.7
       Fresh futures-io v0.3.16
       Fresh pin-utils v0.1.0
       Fresh pin-project-lite v0.1.12
       Fresh smallvec v1.6.1
       Fresh pkg-config v0.3.19
       Fresh ppv-lite86 v0.2.10
       Fresh scopeguard v1.1.0
       Fresh matches v0.1.8
       Fresh convert_case v0.4.0
       Fresh byteorder v1.4.3
       Fresh unicode-segmentation v1.8.0
       Fresh percent-encoding v2.1.0
       Fresh ucd-trie v0.1.3
       Fresh itoa v0.4.7
       Fresh tinyvec_macros v0.1.0
       Fresh copyless v0.1.5
       Fresh either v1.6.1
       Fresh bytes v1.0.1
       Fresh match_cfg v0.1.0
       Fresh fnv v1.0.7
       Fresh version_check v0.1.5
       Fresh quick-error v1.2.3
       Fresh linked-hash-map v0.5.4
       Fresh adler32 v1.2.0
       Fresh adler v1.0.2
       Fresh regex-syntax v0.6.25
       Fresh hashbrown v0.11.2
       Fresh cpufeatures v0.1.5
       Fresh mime v0.3.16
       Fresh color_quant v1.1.0
       Fresh opaque-debug v0.3.0
       Fresh unicode-width v0.1.8
       Fresh plotters-backend v0.3.2
       Fresh language-tags v0.2.2
       Fresh jpeg-decoder v0.1.22
       Fresh same-file v1.0.6
       Fresh base64 v0.13.0
       Fresh weezl v0.1.5
       Fresh bytemuck v1.7.2
       Fresh ansi_term v0.11.0
       Fresh strsim v0.8.0
       Fresh float-ord v0.2.0
       Fresh vec_map v0.8.2
       Fresh ttf-parser v0.12.3
       Fresh instant v0.1.10
       Fresh cmake v0.1.45
       Fresh lock_api v0.4.4
       Fresh heck v0.3.3
       Fresh pest v2.1.3
       Fresh tinyvec v1.3.1
       Fresh form_urlencoded v1.0.1
       Fresh unicode-bidi v0.3.5
       Fresh tracing-core v0.1.18
       Fresh http v0.2.4
       Fresh lru-cache v0.1.2
       Fresh deflate v0.8.6
       Fresh miniz_oxide v0.3.7
       Fresh fxhash v0.2.1
       Fresh buf-min v0.4.0
       Fresh bytestring v1.0.0
       Fresh libc v0.2.119
       Fresh proc-macro2 v1.0.28
       Fresh log v0.4.14
       Fresh futures-core v0.3.16
       Fresh proc-macro-hack v0.5.19
       Fresh bitflags v1.2.1
       Fresh proc-macro-nested v0.1.7
       Fresh futures-task v0.3.16
       Fresh crc32fast v1.2.1
       Fresh unicode-normalization v0.1.19
       Fresh semver-parser v0.10.2
       Fresh typenum v1.13.0
       Fresh ryu v1.0.5
       Fresh const_fn v0.4.8
       Fresh memchr v2.4.0
       Fresh walkdir v2.3.2
       Fresh textwrap v0.11.0
       Fresh gif v0.11.2
       Fresh plotters-svg v0.3.1
       Fresh quote v1.0.9
       Fresh net2 v0.2.37
       Fresh futures-channel v0.3.16
       Fresh iovec v0.1.4
       Fresh signal-hook-registry v1.4.0
       Fresh num_cpus v1.13.0
       Fresh parking_lot_core v0.8.3
       Fresh getrandom v0.1.16
       Fresh num-traits v0.2.14
       Fresh semver v0.11.0
       Fresh idna v0.2.3
       Fresh generic-array v0.14.4
       Fresh aho-corasick v0.7.18
       Fresh hostname v0.3.1
       Fresh miniz_oxide v0.4.4
       Fresh tracing v0.1.26
       Fresh standback v0.2.17
       Fresh atty v0.2.14
       Fresh brotli-sys v0.3.2
       Fresh indexmap v1.7.0
       Fresh getrandom v0.2.3
       Fresh png v0.16.8
       Fresh time v0.1.44
       Fresh encoding_rs v0.8.28
       Fresh nom v4.2.3
       Fresh httparse v1.4.1
       Fresh dirs-sys-next v0.1.2
       Fresh socket2 v0.3.19
       Fresh unicase v2.6.0
       Fresh syn v1.0.74
       Fresh mio v0.6.23
       Fresh parking_lot v0.11.1
       Fresh threadpool v1.8.1
       Fresh rand_core v0.5.1
       Fresh num-integer v0.1.44
       Fresh url v2.2.2
       Fresh rustc_version v0.3.3
       Fresh regex v1.5.4
       Fresh freetype-sys v0.13.1
       Fresh resolv-conf v0.7.0
       Fresh block-buffer v0.9.0
       Fresh digest v0.9.0
       Fresh flate2 v1.0.20
       Fresh expat-sys v2.1.6
       Fresh rand_core v0.6.3
       Fresh brotli2 v0.3.2
       Fresh proc-macro-error-attr v1.0.4
       Fresh dirs-next v2.0.0
       Fresh clap v2.33.3
       Fresh colored v1.9.3
       Fresh futures-macro v0.3.16
       Fresh mio-uds v0.6.8
       Fresh pin-project-internal v0.4.28
       Fresh derive_more v0.99.16
       Fresh actix-macros v0.1.3
       Fresh serde_derive v1.0.127
       Fresh rand_chacha v0.2.2
       Fresh thiserror-impl v1.0.30
       Fresh enum-as-inner v0.3.3
       Fresh async-trait v0.1.51
       Fresh pin-project-internal v1.0.8
       Fresh time-macros-impl v0.1.2
       Fresh num-iter v0.1.42
       Fresh servo-fontconfig-sys v5.1.0
       Fresh sha-1 v0.9.7
       Fresh num-rational v0.3.2
       Fresh v_escape_derive v0.8.4
       Fresh proc-macro-error v1.0.4
       Fresh rand_chacha v0.3.1
       Fresh chrono v0.4.19
       Fresh freetype v0.7.0
       Fresh actix-web-codegen v0.4.0
       Fresh futures-util v0.3.16
       Fresh tokio v0.2.25
       Fresh pin-project v0.4.28
       Fresh actix-threadpool v0.3.3
       Fresh serde v1.0.127
       Fresh thiserror v1.0.30
       Fresh rand v0.7.3
       Fresh time-macros v0.1.1
       Fresh pin-project v1.0.8
       Fresh servo-fontconfig v0.5.1
       Fresh image v0.23.14
       Fresh rand v0.8.4
       Fresh structopt-derive v0.4.18
       Fresh v_escape v0.15.0
       Fresh mime_guess v2.0.3
       Fresh simple_logger v1.13.0
       Fresh tokio-util v0.3.1
       Fresh actix-rt v1.1.1
       Fresh actix-service v1.0.6
       Fresh futures-executor v0.3.16
       Fresh serde_json v1.0.66
       Fresh tracing-futures v0.2.5
       Fresh time v0.2.27
       Fresh serde_urlencoded v0.7.0
       Fresh pathfinder_simd v0.5.1
       Fresh plotters-bitmap v0.3.1
       Fresh actix-router v0.2.7
       Fresh structopt v0.3.26
       Fresh reservoir-sampling v0.5.1
       Fresh v_htmlescape v0.12.0
       Fresh actix-codec v0.3.0
       Fresh futures v0.3.16
       Fresh cookie v0.14.4
       Fresh h2 v0.2.7
       Fresh pathfinder_geometry v0.5.1
       Fresh actix-utils v2.0.0
       Fresh trust-dns-proto v0.19.7
       Fresh font-kit v0.10.1
       Fresh trust-dns-resolver v0.19.7
       Fresh actix-server v1.0.4
       Fresh actix-tls v2.0.0
       Fresh plotters v0.3.1
       Fresh actix-connect v2.0.0
       Fresh actix-testing v1.0.1
       Fresh fastq2comp v0.3.0 (https://github.com/ChristelKrueger/Library_Base_Compositions#ee6fc6d3)
       Fresh actix-http v2.2.1
       Fresh awc v2.0.3
       Fresh actix-web v3.3.2
       Fresh actix-files v0.5.0
   Compiling librarian-server v0.1.0 (/data/private/Librarian-Server/server)
     Running `rustc --crate-name server --edition=2018 src/bin/server.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C metadata=27e648173680b7c8 -C extra-filename=-27e648173680b7c8 --out-dir /data/private/Librarian-Server/server/target/release/deps -L dependency=/data/private/Librarian-Server/server/target/release/deps --extern actix_files=/data/private/Librarian-Server/server/target/release/deps/libactix_files-d1acb451a1af0a2c.rlib --extern actix_web=/data/private/Librarian-Server/server/target/release/deps/libactix_web-242add67f47e6615.rlib --extern base64=/data/private/Librarian-Server/server/target/release/deps/libbase64-b8523cb39ad32992.rlib --extern fastq2comp=/data/private/Librarian-Server/server/target/release/deps/libfastq2comp-0befb43f8a9f885e.rlib --extern futures=/data/private/Librarian-Server/server/target/release/deps/libfutures-5947450b161405c6.rlib --extern librarian_server=/data/private/Librarian-Server/server/target/release/deps/liblibrarian_server-256266a6834a7687.rlib --extern log=/data/private/Librarian-Server/server/target/release/deps/liblog-f96548cfc8efd645.rlib --extern serde=/data/private/Librarian-Server/server/target/release/deps/libserde-e1f84783bc93c0c2.rlib --extern serde_json=/data/private/Librarian-Server/server/target/release/deps/libserde_json-8429a7f918da9965.rlib --extern simple_logger=/data/private/Librarian-Server/server/target/release/deps/libsimple_logger-e96822f73ab94688.rlib --extern structopt=/data/private/Librarian-Server/server/target/release/deps/libstructopt-cd4788896465e801.rlib --extern thiserror=/data/private/Librarian-Server/server/target/release/deps/libthiserror-8d39d7dbdc763a7c.rlib -L native=/data/private/Librarian-Server/server/target/release/build/brotli-sys-56c4b6b9048a4f83/out -L native=/usr/lib64 -L native=/usr/lib64 -L native=/usr/lib64`
error: there is no argument named `default`
  --> src/bin/server.rs:56:60
   |
56 |                 warn!("{:?} not found, using default value {default:?}", &key);
   |                                                            ^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `librarian-server`

Caused by:
  process didn't exit successfully: `rustc --crate-name server --edition=2018 src/bin/server.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C metadata=27e648173680b7c8 -C extra-filename=-27e648173680b7c8 --out-dir /data/private/Librarian-Server/server/target/release/deps -L dependency=/data/private/Librarian-Server/server/target/release/deps --extern actix_files=/data/private/Librarian-Server/server/target/release/deps/libactix_files-d1acb451a1af0a2c.rlib --extern actix_web=/data/private/Librarian-Server/server/target/release/deps/libactix_web-242add67f47e6615.rlib --extern base64=/data/private/Librarian-Server/server/target/release/deps/libbase64-b8523cb39ad32992.rlib --extern fastq2comp=/data/private/Librarian-Server/server/target/release/deps/libfastq2comp-0befb43f8a9f885e.rlib --extern futures=/data/private/Librarian-Server/server/target/release/deps/libfutures-5947450b161405c6.rlib --extern librarian_server=/data/private/Librarian-Server/server/target/release/deps/liblibrarian_server-256266a6834a7687.rlib --extern log=/data/private/Librarian-Server/server/target/release/deps/liblog-f96548cfc8efd645.rlib --extern serde=/data/private/Librarian-Server/server/target/release/deps/libserde-e1f84783bc93c0c2.rlib --extern serde_json=/data/private/Librarian-Server/server/target/release/deps/libserde_json-8429a7f918da9965.rlib --extern simple_logger=/data/private/Librarian-Server/server/target/release/deps/libsimple_logger-e96822f73ab94688.rlib --extern structopt=/data/private/Librarian-Server/server/target/release/deps/libstructopt-cd4788896465e801.rlib --extern thiserror=/data/private/Librarian-Server/server/target/release/deps/libthiserror-8d39d7dbdc763a7c.rlib -L native=/data/private/Librarian-Server/server/target/release/build/brotli-sys-56c4b6b9048a4f83/out -L native=/usr/lib64 -L native=/usr/lib64 -L native=/usr/lib64` (exit status: 1)
```

**Comment by s-andrews** [comment]
The latest changes seem to have fixed this.  I still get a bunch of poison warnings when it starts but it does keep running and the cli now works.
